language: python
python:
- '3.5'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda2/bin:$PATH
- hash -r
- conda update --yes conda
- conda info -a
- conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION xarray netCDF4
- source activate test-environment
install:
- python setup.py install
- wget https://www.dropbox.com/s/mmgxijdvhemdzoy/foam_2011-01-01.nc
script:
- pycovjson-convert -i foam_2011-01-01.nc -v SALTY
- test -s coverage.covjson


deploy:
  provider: pypi
  user: rileywilliams
  password:
    secure: eZeb5zRnUPVY1vezZwAZcmz0lPlGIccgHIM6xotC1VC8TneBl5nrpZaSnNgNULsbh8ZjdK6ucB4nQozJ7jPMeehJsTkZSvMAniAbK6c9vIcQ9nnflfTg3PMtpaIUGGc2HxjiNKQKJG3Cru+NfEbAEnVnJ0uswDD+EwBT5hIpUjsiMYL3j/9zilgd4SNShzaqwCI5lLjfpa4fWwMkTGgt0iMPzCJnC4j1vL6YBhuCmexcb160jWzh2C7GsIu3DXZRm7VIyfCNCk8nO87otiYE5CqQgS8KR5GiZQVKiOt7NFJ+6kQghwtuxIRZ307vCieiQY5iiWpgLvJVOqPFXNo4tVjdU27ymcTOyadmNnRamHRoEOFKWSXb4OGrbHvxUW/QdYE3TS/kscs1TZJQumrfuV1cBL9OhN4zjptXwmlswQkSny/aQ5pykYBB6K9jELJYG+N0XJMnteaFdQh5/URgm+qk6y07eVCxGuQzllDOHoauF7kJ2z2U/rBs/lxXXXKBFUVl7Zf73n8Tyg5Dwr85GF16oq1LEYDiqRVM3rgqE5a8+xWDOGDX2w/OtcNE75JNsn9ig7eVZiF7kphMSxhykjtL/OyP3fXCOWKDTrjEEzKXlgNjD7Ftz/+McuQslRhinMSCgoSVaNoKGvbSkxl3/LwS6Mz/b4vND1tW1SKsvvM=
  on:
    tags: true
    repo: Reading-eScience-Centre/pycovjson
