language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"


install:


  - pip install numpy xarray
  - python setup.py install

script:

  - python3 pycovjson/cli/convert.py -i pycovjson/polcoms.nc -v sst

