language: python
python:

  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION xarray netCDF4
  - source activate test-environment
  - python setup.py install

install:

 - conda install -c rileywilliams pycovjson
 - wget https://www.dropbox.com/s/mmgxijdvhemdzoy/foam_2011-01-01.nc

script:

  - pycovjson-convert -i foam_2011-01-01.nc -v sst
  - cat coverage.json | more

