package:
  name: pycovjson
  version: "0.3.4"

source:

  git_url: https://github.com/Reading-eScience-Centre/pycovjson.git

requirements:
  build:
    - python
    - setuptools
    - hdf5
  run:
    - python

test:
  imports:
    - pycovjson

about:
  home: https://github.com/Reading-eScience-Centre/pycovjson
  license: BSD
  license_file: LICENSE